# Nome visual do Workflow
name: GameHub CI

# Executa este workflow quando houver push no main 
# ou PR fazendo merge para o main
on:
  push:
    branches:
      - main

  pull-request:
    branches:
      - main

# Vamos usar o validate
# jobs podem conter
# validate:
# test:
# build:
# security:
validate:
  name: Validar GameHub # Nome do Job
  runs-on: ubuntu-latest # Executa no runner (ambiente)

defaults:
  run:
    working-directory: backend # Procura a past backend ANTES de executar o Action

steps:
  - name: Checkout do Repositório # Quando o runner nasce ele procura o repositório
    uses: actions/checkout@v7 # @v7 versão mais recente

  - name: Fazer Setup do Node.js
    uses: actions/setup-node@v7 # Diz para o runner rodar no ambiente node
    with:
      node-version: 24
      cache: npm
      cache-dependency-path: backend/package-lock.json

  - name: Instalar dependências # Instala tudo no Runner (longe do repositório)
    run: npm ci # Não baixa o node_modules novamente, apenas executa.

  # Pede ao node o seguinte:
  # "Leia e valida a sintaxe desse arquivo sem executa-lo"
  - name: Validar sintaxe back-end
    run: |
      node --check server.js
      node --check db.js

  - name: Validar sintaxe front-end
    run: node --check ../public/js/script.js

# package.json
# -> Quais dependências queremos!

# package-lock.json
# -> quais versões queremos!

# npm ci
# -> reproduz o ambiente

# -> DevOps puro